### ISSUE TITLE
Is there any output?

### ISSUE THREAD

**Issue by tterranigma** [yswery/PHP-DNS-SERVER#25]
Awesome project! To my question.

It would be nice to somewhere to log requests. Is there any such capability now?

**Comment by yswery** [comment]
Currently speaking, no there is no logging

However would love to see this come through as a PR if you got time, some foreground output/logging 

In the `ds_handle_query()` method you will find the first entry point where you can see who made the query and what the query was: https://github.com/yswery/PHP-DNS-SERVER/blob/master/src/Server.php#L62

 later in this method the question query is decoded so you will have the ability to print something in there about who did the DNS query and what they asked for and what the response is.

I think thats the best place to start with output logs inside that method, if you are not familiar with the protocol,  a good way to go through this would be to just print out all the variables one by one inside the `ds_handle_query()` method to see what they store as your query the DNS server and that way by trial and error you can see and learn what holds what :)

Would be good to have this logging as some configurable option in order to turn it off/on for those who want it.

**Comment by samuelwilliams** [comment]
It might be worth adding a [PSR Logger](https://github.com/php-fig/log) interface to the constructor or the  aware interface to the class. You could then use a null logger as the default, or implement some other logging library such as [Monolog](https://github.com/Seldaek/monolog).

**Comment by ivanstan** [comment]
Currently working on Event Listeners in Server class, my idea was to create listener and than do the logging inside them. I would also recommend throwing Exception instead of using `ds_handle_query()` in cases where it should lead to stopping server

**Comment by samuelwilliams** [comment]
You can implement it with the EchoLogger in branch version-1
